#
# Module manifest for module 'PSScriptMenuGui'
#
# Generated by: Dan O'Sullivan
# Updated: February 2026
#
# This module provides a graphical menu system for PowerShell scripts using WPF and data binding.
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSScriptMenuGui.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Unique identifier for this module
GUID = '103460b8-4f8b-471c-8f70-41e493070656'

# Author of this module
Author = "Dan O'Sullivan"

# Company or vendor of this module
CompanyName = 'Open Source'

# Copyright statement for this module
Copyright = "(c) Dan O'Sullivan. Released under the MIT License."

# Description of the functionality provided by this module
Description = 'Create a graphical menu for PowerShell scripts using CSV configuration and XAML with modern WPF data binding. Supports custom colors, icons, sections, and script execution.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# PowerShell editions this module is compatible with
CompatiblePSEditions = @('Desktop', 'Core')

# Required .NET Framework/Core assemblies
RequiredAssemblies = @('PresentationFramework', 'PresentationCore', 'WindowsBase')

# Functions to export
FunctionsToExport = @(
    'Show-ScriptMenuGui'
    'New-ScriptMenuGuiExample'
)

# Cmdlets to export (if any)
CmdletsToExport = @()

# Variables to export (if any)
VariablesToExport = @()

# Aliases to export (if any)
AliasesToExport = @()

# Private functions to keep internal
PrivateFunctionPrefix = ''

# Modules that must be imported into the global environment before this module is imported
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this release
# ModuleList = @()

# List of all files packaged with this release
# FileList = @()

# Private data to pass to the module specified in RootModule/RootScript; this may also contain a PSData hashtable with additional metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('GUI', 'Menu', 'WPF', 'CSV', 'XAML', 'Windows', 'Script', 'Automation')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/weebsnore/PowerShell-Script-Menu-Gui/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/weebsnore/PowerShell-Script-Menu-Gui'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Version 2.0.0: Refactored to use WPF data binding instead of string concatenation. Improved maintainability and scalability.'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Show-ScriptMenuGui',
    'New-ScriptMenuGuiExample'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PSEdition_Desktop','PSEdition_Core','Windows')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/weebsnore/PowerShell-Script-Menu-Gui/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/weebsnore/PowerShell-Script-Menu-Gui'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

